services:
#    regis.command_handler.repository.disable_inspections:
#        class: Regis\Application\CommandHandler\Repository\DisableInspections
#        arguments: [ '@regis.repository.repositories' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Repository\DisableInspections }
#
#    regis.command_handler.repository.enable_inspections:
#        class: Regis\Application\CommandHandler\Repository\EnableInspections
#        arguments: [ '@regis.repository.repositories' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Repository\EnableInspections }
#
#    regis.command_handler.users.create_admin:
#        class: Regis\Application\CommandHandler\User\CreateAdmin
#        arguments: [ '@regis.repository.users', '@security.password_encoder' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\User\CreateAdmin }
#
#
#    regis.command_handler.teams.create:
#        class: Regis\Application\CommandHandler\Team\Create
#        arguments: [ '@regis.repository.teams' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Team\Create }
#
#    regis.command_handler.teams.add_member:
#        class: Regis\Application\CommandHandler\Team\AddMember
#        arguments: [ '@regis.repository.teams', '@regis.repository.users' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Team\AddMember }
#
#    regis.command_handler.teams.remove_member:
#        class: Regis\Application\CommandHandler\Team\RemoveMember
#        arguments: [ '@regis.repository.teams', '@regis.repository.users' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Team\RemoveMember }
#
#    regis.command_handler.teams.leave:
#        class: Regis\Application\CommandHandler\Team\Leave
#        arguments: [ '@regis.repository.teams' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Team\Leave }
#
#    regis.command_handler.teams.add_repository:
#        class: Regis\Application\CommandHandler\Team\AddRepository
#        arguments: [ '@regis.repository.teams', '@regis.repository.repositories' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Team\AddRepository }
#
#    regis.command_handler.teams.remove_repository:
#        class: Regis\Application\CommandHandler\Team\RemoveRepository
#        arguments: [ '@regis.repository.teams', '@regis.repository.repositories' ]
#        tags:
#            - { name: tactician.handler, command: Regis\Application\Command\Team\RemoveRepository }
