repositories_list:
    path:      /repositories
    defaults:  { _controller: RegisBackendBundle:Repositories:list }
    methods:   GET

repositories_detail:
    path:      /repositories/{identifier}
    defaults:  { _controller: RegisBackendBundle:Repositories:detail }
    requirements: { identifier: "[^/]+/[^/]+" }
    methods:   GET

repositories_setup_webhook:
    path:      /repositories/{identifier}/webhook/setup
    defaults:  { _controller: RegisBackendBundle:Repositories:setupWebhook }
    requirements: { identifier: "[^/]+/[^/]+" }
    methods:   POST

repositories_new:
    path:      /repositories/new
    defaults:  { _controller: RegisBackendBundle:RepositoryCreator:new }
    methods:   GET

repositories_create:
    path:      /repositories/create
    defaults:  { _controller: RegisBackendBundle:RepositoryCreator:create }
    methods:   POST

repositories_remote_list:
    path:      /repositories/remote
    defaults:  { _controller: RegisBackendBundle:RepositoryCreator:remoteRepositoriesList }
    methods:   GET
    options:   { expose: true }

repositories_edit:
    path:      /repositories/{identifier}/edit
    defaults:  { _controller: RegisBackendBundle:Repositories:edit }
    requirements: { identifier: "[^/]+/[^/]+" }
    methods:   GET|POST

inspection_retry:
    path:      /inspections/{id}/retry
    defaults:  { _controller: RegisBackendBundle:Inspections:retry }
    methods:   POST

report_detail:
    path:      /reports/{id}
    defaults:  { _controller: RegisBackendBundle:Auth:detail }
    methods:   GET