Regis\Application\Entity\Analysis:
    type: entity
    table: analysises

    id:
        id:
            type: guid
            generator: { strategy: UUID }

    fields:
        result:
            type: text

    manyToOne:
        inspection:
          targetEntity: Inspection
          inversedBy: analysises
          joinColumn:
            name: inspection_id
            referencedColumnName: id