Regis\Application\Entity\Inspection\Analysis:
    type: entity
    table: analyses

    id:
        id:
            type: guid
            generator: { strategy: UUID }

    fields:
        type:
            type: string
        status:
            type: string

    oneToMany:
        violations:
          targetEntity: Regis\Application\Entity\Inspection\Violation
          mappedBy: analysis
          cascade: [ 'persist', 'merge' ]

    manyToOne:
        report:
          targetEntity: Regis\Application\Entity\Inspection\Report
          inversedBy: analyses
          joinColumn:
            name: report_id
            referencedColumnName: id