Regis\Application\Entity\Inspection:
    type: entity
    table: inspections
    inheritanceType: SINGLE_TABLE

    discriminatorColumn:
        name: type
        type: string

    discriminatorMap:
        github_pr: Regis\Application\Entity\Github\PullRequestInspection

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        createdAt:
            type: datetimetz
        startedAt:
            type: datetimetz
            nullable: true
        finishedAt:
            type: datetimetz
            nullable: true
        status:
            type: string
        failureTrace:
            type: text
        base:
            type: string
        head:
            type: string

    oneToOne:
        report:
          targetEntity: Regis\Application\Entity\Inspection\Report
          mappedBy: inspection
          cascade: [ 'persist', 'merge' ]

    manyToOne:
        repository:
          targetEntity: Regis\Application\Entity\Repository
          inversedBy: inspections
          joinColumn:
            name: repository_id
            referencedColumnName: identifier