Regis\Application\Entity\Repository:
    type: entity
    table: repositories

    id:
        identifier:
            type: string
            generator: { strategy: NONE }

    fields:
        sharedSecret:
            type: string

    oneToMany:
        inspections:
          targetEntity: Inspection
          mappedBy: repository