Regis\Application\Model\Repository:
    type: entity
    table: repositories

    id:
        identifier:
            type: string
            generator: { strategy: NONE }

    fields:
        sharedSecret:
            type: string