language: php

sudo: false

git:
    # dirty hack to make this test work tests/Regis/Infrastructure/Vcs/RepositoryTest::testGetDiff
    depth: 5000

cache:
    directories:
        - $HOME/.composer/cache

branches:
    only:
        - master

php:
    - 7.1

matrix:
    fast_finish: true

install:
    - composer install --optimize-autoloader --no-interaction
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then composer require satooshi/php-coveralls '^1.0'; fi

script:
    - make tests

after_script:
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then php vendor/bin/coveralls -v; fi
