language: php

sudo: false

git:
    # dirty hack to make this test work tests/Regis/Infrastructure/Vcs/RepositoryTest::testGetDiff
    depth: 5000

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0

env:
    - SYMFONY_DEPRECATIONS_HELPER=disabled

matrix:
    fast_finish: true

before_install:
    - composer self-update

install:
    - composer install --optimize-autoloader --no-interaction --no-scripts ${COMPOSER_FLAGS}
    - composer require satooshi/php-coveralls '^1.0'

script:
    - make tests

after_script:
    - php vendor/bin/coveralls -v
