language: php

sudo: false

php:
    - 7.0

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install:
    - composer install --optimize-autoloader --no-interaction --no-scripts ${COMPOSER_FLAGS}

script:
    - ./vendor/bin/phpunit
