language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 7.0

matrix:
    fast_finish: true

before_install:
    - composer self-update

install:
    - composer install --optimize-autoloader --no-interaction --no-scripts ${COMPOSER_FLAGS}
    - composer require satooshi/php-coveralls

script:
    - ./vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v
