services:
    regis.github.github:
        class: Github\Client
        public: false

    regis.github.client_factory:
        class: Regis\Infrastructure\Github\ClientFactory
        arguments: [ '@regis.github.github', '@logger' ]
        tags:
            - { name: monolog.logger, channel: github }

    regis.github.event_transformer:
        class: Regis\Application\Github\EventTransformer

    regis.github.payload_validator:
        class: Regis\Application\Github\PayloadValidator
        arguments: [ '@regis.repository.repositories' ]
