services:
    regis.github.cached_http_client:
        class: Github\HttpClient\CachedHttpClient
        arguments:
            - { cache_dir: '%kernel.cache_dir%/github-api-cache' }
        public: false

    regis.github.github:
        class: Github\Client
        arguments: [ '@regis.github.cached_http_client' ]
        public: false

    regis.github.client_factory:
        class: Regis\Infrastructure\Github\ClientFactory
        arguments: [ '@regis.github.github', '@logger' ]
        tags:
            - { name: monolog.logger, channel: github }

    regis.github.event_transformer:
        class: Regis\Application\Github\EventTransformer

    regis.github.payload_validator:
        class: Regis\Application\Github\PayloadValidator
        arguments: [ '@regis.repository.repositories' ]
