old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     '%rabbitmq_port%'
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost:    '%rabbitmq_vhost%'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            #use_socket: true # default false
    producers:
        analysis_inspection:
            connection: default
            exchange_options: {name: 'analysis-inspection', type: direct}

        analysis_status:
            connection: default
            exchange_options: {name: 'analysis-status', type: direct}

    consumers:
        analysis_inspection:
            connection: default
            exchange_options: {name: 'analysis-inspection', type: direct}
            queue_options: {name: 'analysis-inspection'}
            callback: regis.analysis.worker.inspection_event
            enable_logger: true

        github_analysis_status:
            connection: default
            exchange_options: {name: 'analysis-status', type: direct}
            queue_options:
                name: 'gh-analysis-status'
                routing_keys: [ analysis.github_pr.status ]
            callback: regis.github.worker.analysis_status
            enable_logger: true

        bitbucket_analysis_status:
            connection: default
            exchange_options: {name: 'analysis-status', type: direct}
            queue_options:
                name: 'bitbucket-analysis-status'
                routing_keys: [ analysis.bitbucket_pr.status ]
            callback: regis.bitbucket.worker.analysis_status
            enable_logger: true
