old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     '%rabbitmq_port%'
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost:    '%rabbitmq_vhost%'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            #use_socket: true # default false
    producers:
        webhook_event:
            connection:       default
            exchange_options: {name: 'webhook-event', type: direct}
    consumers:
        webhook_event:
            connection:       default
            exchange_options: {name: 'webhook-event', type: direct}
            queue_options:    {name: 'webhook-event'}
            callback:         regis.worker.webhook_event
            enable_logger:    true