regis_webhooks:
    inspections:
        phpcs:
            options: [ '--standard=psr1,psr2' ]
        phpmd:
            rulesets: [ 'codesize', 'unusedcode', 'naming', 'controversial', 'design', 'cleancode' ]