regis_webhooks:
    inspections:
        phpcs:
            options: [ '--standard=psr1,psr2' ]
        phpmd:
            rulesets: [ 'codesize', 'unusedcode', 'naming', 'controversial', 'design', 'cleancode' ]

    repositories:
        -
            identifier: K-Phoen/test
            secret: '%test_repo_secret%'
        -
            identifier: K-Phoen/regis
            secret: '%test_repo_secret%'
