regis_webhooks:
    inspections:
        phpcs:
            options: [ '--standard=psr1,psr2' ]

    repositories:
        -
            identifier: K-Phoen/test
            secret: '%test_repo_secret%'