regis_analysis:
    inspections:
        phpcs:
            standards: [ 'psr1', 'psr2' ]
        phpmd:
            rulesets: [ 'codesize', 'unusedcode', 'naming', 'controversial', 'design', 'cleancode' ]
