snc_redis:
    clients:
        violations:
            type: predis
            alias: violations
            dsn: "%env(REDIS_URL)%"
        sessions:
            type: predis
            alias: sessions
            dsn: "%env(REDIS_URL)%"

    session:
        client: sessions
        prefix: sessions
