services:
    regis.tactician.middleware.logger.formatter:
        class: League\Tactician\Logger\Formatter\ClassPropertiesFormatter

    regis.tactician.middleware.logger:
        class: League\Tactician\Logger\LoggerMiddleware
        arguments: [ '@regis.tactician.middleware.logger.formatter', '@logger' ]
        tags:
            - { name: monolog.logger, channel: command_bus }

    regis.tactician.middleware.security:
        class: Regis\AppContext\Application\CommandHandler\Middleware\Security
        arguments: [ '@rulerz', '@regis.security.context' ]
        tags:
            - { name: monolog.logger, channel: command_bus }

tactician:
    commandbus:
        default:
            middleware:
                - regis.tactician.middleware.logger
                - regis.tactician.middleware.security
                - tactician.middleware.command_handler
