imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

framework:
  serializer:
      cache: serializer.mapping.cache.apc
  session:
      handler_id: snc_redis.session.handler

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
