imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: bundles/knpu_oauth2_client.yml }
    - { resource: bundles/kphoen_rulerz.yml }
    - { resource: bundles/regis_analysis.yml }
    - { resource: bundles/swarrot.yml }
    - { resource: bundles/snc_redis.yml }
    - { resource: bundles/tactician.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

    phpcs_binary: '%kernel.root_dir%/../vendor/bin/phpcs'
    phpmd_binary: '%kernel.root_dir%/../vendor/bin/phpmd'
    phpstan_binary: '%kernel.root_dir%/../vendor/bin/phpstan'
    composer_binary: '%kernel.root_dir%/../vendor/bin/composer'

    repositories_directory: '%kernel.root_dir%/../var/repositories'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enable_annotations: false
    cache:
        pools:
            serializer: ~
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            Regis\AnalysisContext:
                type: yml
                is_bundle: false
                dir: '%kernel.root_dir%/../src/AnalysisContext/Domain/Entity/config'
                prefix: Regis\AnalysisContext\Domain\Entity
                alias: RegisAnalysisContext
            Regis\AppContext:
                type: yml
                is_bundle: false
                dir: '%kernel.root_dir%/../src/AppContext/Domain/Entity/config'
                prefix: Regis\AppContext\Domain\Entity
                alias: RegisAppContext
            Regis\BitbucketContext:
                type: yml
                is_bundle: false
                dir: '%kernel.root_dir%/../src/BitbucketContext/Domain/Entity/config'
                prefix: Regis\BitbucketContext\Domain\Entity
                alias: RegisBitbucketContext
            Regis\GithubContext:
                type: yml
                is_bundle: false
                dir: '%kernel.root_dir%/../src/GithubContext/Domain/Entity/config'
                prefix: Regis\GithubContext\Domain\Entity
                alias: RegisGithubContext
