imports:
    - { resource: bundles/sentry.yml }
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

#framework:
#  serializer:
#      cache: serializer.mapping.cache.apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: nested
        sentry:
            type: raven
            dsn: "%env(SENTRY_DSN)%"
            level: alert
        nested:
            type: stream
            path: "php://stderr"
            level: debug
        console:
            type: console
