auth:
    resource: "@RegisAuthBundle/Resources/config/routing.yml"

app:
    resource: "@RegisAppBundle/Resources/config/routing.yml"

webhooks:
    resource: "@RegisWebhooksBundle/Resources/config/routing.yml"
    prefix: webhook

backend:
    resource: "@RegisBackendBundle/Resources/config/routing.yml"
    prefix: backend

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"