# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        regis_user_provider:
            id: regis.app.user_account_provider

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        webhooks:
            pattern: ^/webhook
            security: false

        main:
            pattern: ^/
            provider: regis_user_provider
            switch_user: true
            anonymous: ~
            remember_me:
                secret: '%secret%'
                always_remember_me: true
            guard:
                authenticators:
                    - regis.github.authenticator
                    - regis.bitbucket.authenticator
                entry_point: regis.github.authenticator
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
