Regis\AppContext\Domain\Entity\GithubProfile:
    type: entity
    table: user_github

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        username:
            type: string

    oneToOne:
        user:
            targetEntity: User
            inversedBy: githubProfile
            joinColumn:
                name: user_id
                referencedColumnName: id
