Regis\GithubContext\Domain\Entity\GithubDetails:
    type: entity
    table: user_github

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        remoteId:
            type: integer
        username:
            type: string
        accessToken:
            type: string

    oneToOne:
        user:
            targetEntity: UserAccount
            cascade: [persist]
            inversedBy: details
