Regis\GithubContext\Domain\Entity\Repository:
    type: entity
    table: repository

    discriminatorColumn:
        name: type
        type: string

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        identifier:
            type: string
        type:
            type: string
        sharedSecret:
            type: string
        isInspectionEnabled:
            type: boolean
            options: { default: 1 }

    manyToMany:
        teams:
            targetEntity: Team
            mappedBy: repositories

    manyToOne:
        owner:
          targetEntity: User
          inversedBy: repositories
          joinColumn:
            name: owner_id
            referencedColumnName: id

    oneToMany:
        inspections:
          targetEntity: PullRequestInspection
          mappedBy: repository
