Regis\GithubContext\Domain\Entity\Repository:
    type: entity
    table: repository

    discriminatorColumn:
        name: type
        type: string

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        identifier:
            type: string
        type:
            type: string
        sharedSecret:
            type: string
        isInspectionEnabled:
            type: boolean
        isFlightModeEnabled:
            type: boolean

    manyToOne:
        owner:
          targetEntity: UserAccount
          joinColumn:
            name: owner_id
            referencedColumnName: id

    oneToMany:
        inspections:
          targetEntity: PullRequestInspection
          mappedBy: repository
