Regis\GithubContext\Domain\Entity\User:
    type: entity
    table: user_account

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        username:
            type: string
        roles:
            type: simple_array

    oneToOne:
        details:
            targetEntity: GithubDetails
            mappedBy: user
            cascade: [persist]

    oneToMany:
        repositories:
            targetEntity: Repository
            mappedBy: owner

        ownedTeams:
            targetEntity: Team
            mappedBy: owner

    manyToMany:
        teams:
            targetEntity: Team
            mappedBy: members
