Regis\BitbucketContext\Domain\Entity\BitbucketDetails:
    type: entity
    table: user_bitbucket

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        remoteId:
            type: string
        accessToken:
            type: string

    oneToOne:
        user:
            targetEntity: UserAccount
            cascade: [persist]
