Regis\BitbucketContext\Domain\Entity\BitbucketDetails:
    type: entity
    table: user_bitbucket

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        remoteId:
            type: string
        accessToken:
            type: string

    oneToOne:
        user:
            targetEntity: User
            inversedBy: details
            joinColumn:
              name: user_id
              referencedColumnName: id
