Regis\BitbucketContext\Domain\Entity\UserAccount:
    type: entity
    table: user_account

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    oneToOne:
        details:
            targetEntity: BitbucketDetails
            mappedBy: user

