Regis\BitbucketContext\Domain\Entity\User:
    type: entity
    table: users

    id:
        id:
            type: string
            generator: { strategy: NONE }

    fields:
        username:
            type: string
            unique: true
        bitbucketId:
            type: integer
            nullable: true
        bitbucketAccessToken:
            type: string
            nullable: true
        roles:
            type: simple_array

    oneToMany:
        repositories:
          targetEntity: Repository
          mappedBy: owner
