Regis\BitbucketContext\Domain\Entity\Violation:
    type: entity
    table: violation

    id:
        id:
            type: guid
            generator: { strategy: UUID }

    fields:
        severity:
            type: smallint
        file:
            type: string
        line:
            type: integer
        description:
            type: text

    manyToOne:
        analysis:
          targetEntity: Analysis
          inversedBy: violations
          joinColumn:
            name: analysis_id
            referencedColumnName: id
