Regis\Domain\Entity\Inspection\Violation:
    type: entity
    table: violations

    id:
        id:
            type: guid
            generator: { strategy: UUID }

    fields:
        severity:
            type: smallint
        file:
            type: string
        line:
            type: integer
        position:
            type: integer
        description:
            type: string

    manyToOne:
        analysis:
          targetEntity: Regis\Domain\Entity\Inspection\Analysis
          inversedBy: violations
          joinColumn:
            name: analysis_id
            referencedColumnName: id