Regis\Domain\Entity\Inspection\Report:
    type: entity
    table: reports

    id:
        id:
            type: guid
            generator: { strategy: UUID }

    fields:
        status:
            type: string

    oneToMany:
        analyses:
          targetEntity: Analysis
          mappedBy: report
          cascade: [ 'persist', 'merge' ]

    oneToOne:
        inspection:
          targetEntity: Regis\Domain\Entity\Inspection
          inversedBy: report
          joinColumn:
            name: inspection_id
            referencedColumnName: id