Regis\Domain\Entity\Repository:
    type: entity
    table: repositories
    inheritanceType: SINGLE_TABLE

    discriminatorColumn:
        name: type
        type: string

    discriminatorMap:
        github: Regis\Domain\Entity\Github\Repository

    id:
        identifier:
            type: string
            generator: { strategy: NONE }

    fields:
        sharedSecret:
            type: string

    manyToMany:
        teams:
          targetEntity: Regis\Domain\Entity\Team
          mappedBy: repositories

    manyToOne:
        owner:
          targetEntity: Regis\Domain\Entity\User
          inversedBy: repositories
          joinColumn:
            name: owner_id
            referencedColumnName: id

    oneToMany:
        inspections:
          targetEntity: Regis\Domain\Entity\Inspection
          mappedBy: repository