version: '2'
services:
    web:
        build: .
        ports:
            - '8080:80'
        volumes:
            - ..:/var/www/html
            - ./apache/sites-enabled:/etc/apache2/sites-enabled
