FROM php:7.0-apache

RUN apt-get update && apt-get install -y --no-install-recommends \
 libpq-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install -j$(nproc) bcmath
RUN docker-php-ext-install -j$(nproc) pdo_pgsql
