version: '2'
services:
    redis:
        image: 'redis:3.2-alpine'
        volumes:
            - ./redis/data:/data:rw
        command: redis-server --appendonly yes

    rabbit:
        image: 'rabbitmq:3.6-management'
        ports:
            - 8081:15672
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
            - RABBITMQ_DEFAULT_VHOST=regis_vhost

    worker:
        build:
            context: .
            dockerfile: ./Dockerfile-worker
        depends_on:
            - rabbit
            - redis
        volumes:
            - ..:/var/www/html
            - ../var/ssh:/root/.ssh
        command: './docker/wait-for-it.sh rabbit:5672 -- ./bin/console rabbitmq:consumer -vvv webhook_event'

    web:
        build:
            context: .
            dockerfile: Dockerfile-web
        depends_on:
            - rabbit
            - worker
        ports:
            - '8080:80'
        volumes:
            - ..:/var/www/html
            - ./apache/sites-enabled:/etc/apache2/sites-enabled
