services:
    regis.inspector:
        class: Regis\Application\Inspector
        arguments:
            - '@regis.vcs.git'
            - '@regis.violation_reporter.duplication_guard'
            - [ '@regis.inspection.code_sniffer' ]

    regis.inspection.code_sniffer:
        class: Regis\Application\Inspection\CodeSniffer
        arguments: [ '@regis.tools.code_sniffer' ]
        public: false

    regis.tools.code_sniffer:
        class: Regis\CodeSniffer\CodeSniffer
        arguments: [ '%phpcs_binary%', '%regis.config.inspections.phpcs%' ]
        public: false

    regis.violation_reporter.github:
        class: Regis\Application\Reporter\Github
        arguments: [ '@regis.github.client' ]
        public: false

    regis.violation_reporter.duplication_guard:
        class: Regis\Application\Reporter\DuplicationGuard
        arguments: [ '@regis.violation_reporter.github', '@regis.violations_cache' ]
        public: false

    regis.violations_cache:
        class: Regis\Application\Inspection\ViolationsCache
        arguments: [ '@snc_redis.violations' ]
        public: false
