services:
    regis.inspector:
        class: Regis\Domain\Inspector
        arguments:
            - '@regis.vcs.git'
            - '@regis.violation_reporter.github'
            - [ '@regis.inspection.code_sniffer' ]

    regis.inspection.fos_php_cs_fixer:
        class: Regis\Domain\Inspection\FosPhpCsFixer
        public: false

    regis.inspection.code_sniffer:
        class: Regis\Domain\Inspection\CodeSniffer
        arguments: [ '%phpcs_binary%' ]
        public: false

    regis.violation_reporter.github:
        class: Regis\Domain\Reporter\Github
        arguments: [ '@regis.github.client' ]
        public: false
