services:
    regis.subscriber.pull_request:
        class: Regis\Bundle\WebhooksBundle\EventListener\PullRequestListener
        arguments: [ '@tactician.commandbus', '@regis.violations_cache' ]
        tags:
            - { name: kernel.event_subscriber }

    regis.subscriber.pull_request_inspection_status:
        class: Regis\Bundle\WebhooksBundle\EventListener\PullRequestInspectionStatusListener
        arguments: [ '@regis.github.client' ]
        tags:
            - { name: kernel.event_subscriber }