services:
    domain.subscriber.pull_request:
        class: Regis\Bundle\WebhooksBundle\EventListener\PullRequestListener
        arguments: [ '@old_sound_rabbit_mq.webhook_event_producer' ]
        tags:
            - { name: kernel.event_subscriber }