services:
    regis.command_handler.run_analyses:
        class: Regis\AnalysisContext\Application\CommandHandler\RunAnalyses
        arguments: [ '@regis.inspector' ]
        tags:
            - { name: tactician.handler, command: Regis\AnalysisContext\Application\Command\RunAnalyses }
