services:
    regis.analysis.inspection_result_listener:
        class: Regis\AnalysisContext\Application\EventListener\InspectionResultListener
        arguments: [ "@regis.kernel.worker.message_publisher" ]
        tags:
            - { name: kernel.event_subscriber }
