Regis\AnalysisContext\Domain\Entity\Analysis:
    type: entity
    table: analysis

    id:
        id:
            type: guid
            generator: { strategy: NONE }

    fields:
        type:
            type: string
        warningsCount:
            type: integer
        errorsCount:
            type: integer

    oneToMany:
        violations:
          targetEntity: Violation
          mappedBy: analysis
          cascade: [ 'persist', 'merge' ]

    manyToOne:
        report:
          targetEntity: Report
          inversedBy: analyses
          joinColumn:
            name: report_id
            referencedColumnName: id
