Regis\AnalysisContext\Domain\Entity\Report:
    type: entity
    table: report

    id:
        id:
            type: guid
            generator: { strategy: UUID }

    fields:
        status:
            type: string
        warningsCount:
            type: integer
        errorsCount:
            type: integer
        rawDiff:
            type: blob

    oneToMany:
        analyses:
          targetEntity: Analysis
          mappedBy: report
          cascade: [ 'persist', 'merge' ]
