services:
    regis.github.command_handler.repository.create:
        class: Regis\GithubContext\Application\CommandHandler\Repository\RegisterRepository
        arguments: [ '@regis.github.repository.repositories', '@regis.random.generator' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Repository\RegisterRepository }

    regis.github.command_handler.repository.define_shared_secret:
        class: Regis\GithubContext\Application\CommandHandler\Repository\DefineSharedSecret
        arguments: [ '@regis.github.repository.repositories' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Repository\DefineSharedSecret }

    regis.github.command_handler.repository.create_webhook:
        class: Regis\GithubContext\Application\CommandHandler\Repository\CreateWebhook
        arguments: [ '@regis.github.client_factory', '@regis.github.repository.repositories' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Repository\CreateWebhook }

    regis.github.command_handler.repository.add_deploy_key:
        class: Regis\GithubContext\Application\CommandHandler\Repository\AddDeployKey
        arguments: [ '@regis.github.client_factory', '@regis.github.repository.repositories' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Repository\AddDeployKey }

    regis.github.command_handler.inspections.schedule:
        class: Regis\GithubContext\Application\CommandHandler\Inspection\SchedulePullRequest
        arguments:
            - '@old_sound_rabbit_mq.analysis_inspection_producer'
            - '@regis.github.repository.repositories'
            - '@regis.github.repository.pull_request_inspections'
            - '@regis.github.client_factory'
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Inspection\SchedulePullRequest }

    regis.github.command_handler.inspections.send_pr_comments:
        class: Regis\GithubContext\Application\CommandHandler\Inspection\SendViolationsAsComments
        arguments: [ '@regis.github.violation_reporter.duplication_guard' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Inspection\SendViolationsAsComments }

    regis.github.command_handler.users.create_or_update_user:
        class: Regis\GithubContext\Application\CommandHandler\User\CreateOrUpdateUser
        arguments: [ '@regis.github.repository.users' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\User\CreateOrUpdateUser }

    regis.command_handler.repository.disable_inspections:
        class: Regis\GithubContext\Application\CommandHandler\Repository\DisableInspections
        arguments: [ '@regis.github.repository.repositories' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Repository\DisableInspections }

    regis.command_handler.repository.enable_inspections:
        class: Regis\GithubContext\Application\CommandHandler\Repository\EnableInspections
        arguments: [ '@regis.github.repository.repositories' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Repository\EnableInspections }

    regis.command_handler.users.create_admin:
        class: Regis\GithubContext\Application\CommandHandler\User\CreateAdmin
        arguments: [ '@regis.github.repository.users', '@security.password_encoder' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\User\CreateAdmin }

    regis.command_handler.teams.create:
        class: Regis\GithubContext\Application\CommandHandler\Team\Create
        arguments: [ '@regis.github.repository.teams' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Team\Create }

    regis.command_handler.teams.add_member:
        class: Regis\GithubContext\Application\CommandHandler\Team\AddMember
        arguments: [ '@regis.github.repository.teams', '@regis.github.repository.users' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Team\AddMember }

    regis.command_handler.teams.remove_member:
        class: Regis\GithubContext\Application\CommandHandler\Team\RemoveMember
        arguments: [ '@regis.github.repository.teams', '@regis.github.repository.users' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Team\RemoveMember }

    regis.command_handler.teams.leave:
        class: Regis\GithubContext\Application\CommandHandler\Team\Leave
        arguments: [ '@regis.github.repository.teams' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Team\Leave }

    regis.command_handler.teams.add_repository:
        class: Regis\GithubContext\Application\CommandHandler\Team\AddRepository
        arguments: [ '@regis.github.repository.teams', '@regis.github.repository.repositories' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Team\AddRepository }

    regis.command_handler.teams.remove_repository:
        class: Regis\GithubContext\Application\CommandHandler\Team\RemoveRepository
        arguments: [ '@regis.github.repository.teams', '@regis.github.repository.repositories' ]
        tags:
            - { name: tactician.handler, command: Regis\GithubContext\Application\Command\Team\RemoveRepository }
