services:
    regis.github.subscriber.pull_request:
        class: Regis\GithubContext\Application\EventListener\PullRequestListener
        arguments: [ '@tactician.commandbus', '@regis.github.violations_cache' ]
        tags:
            - { name: kernel.event_subscriber }

    regis.github.subscriber.pull_request_inspection_status:
        class: Regis\GithubContext\Application\EventListener\PullRequestInspectionStatusListener
        arguments:
            - '@regis.github.client_factory'
            - '@regis.github.repository.repositories'
            - '@regis.github.repository.inspections'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    regis.github.subscriber.pull_request_inspection_report:
        class: Regis\GithubContext\Application\EventListener\PullRequestInspectionReportListener
        arguments: [ '@tactician.commandbus' ]
        tags:
            - { name: kernel.event_subscriber }

    regis.github.subscriber.pull_request_report_as_comments:
        class: Regis\GithubContext\Application\EventListener\PullRequestReviewCommentsListener
        arguments: [ '@tactician.commandbus' ]
        tags:
            - { name: kernel.event_subscriber }
