services:
    regis.github.repository.repositories:
        class: Regis\GithubContext\Infrastructure\Repository\DoctrineRepositories
        arguments: ['@doctrine.orm.entity_manager']

    regis.github.repository.pull_request_inspections:
        class: Regis\GithubContext\Infrastructure\Repository\DoctrinePullRequestInspections
        arguments: [ '@doctrine' ]

    regis.github.repository.users:
        class: Regis\GithubContext\Infrastructure\Repository\DoctrineUsers
        arguments: ['@doctrine.orm.entity_manager']
