services:
    regis.app.remote.github_repositories:
        class: Regis\AppContext\Application\Remote\GithubRepositories
        arguments: [ '@regis.github.client_factory', '@regis.github.repository.users' ]
        public: false

    regis.app.remote.bitbucket_repositories:
        class: Regis\AppContext\Application\Remote\BitbucketRepositories
        arguments: [ '@regis.bitbucket.client_factory', '@regis.bitbucket.repository.users' ]
        public: false

    regis.app.remote.repositories:
        class: Regis\AppContext\Application\Remote\AggregatedRepositories
        arguments:
            - ['@regis.app.remote.bitbucket_repositories', '@regis.app.remote.github_repositories' ]

    regis.app.remote.bitbucket_actions:
        class: Regis\AppContext\Application\Remote\BitbucketActions
        arguments: [ '@tactician.commandbus' ]
        public: false

    regis.app.remote.github_actions:
        class: Regis\AppContext\Application\Remote\GithubActions
        arguments: [ '@tactician.commandbus' ]
        public: false

    regis.app.remote.actions:
        class: Regis\AppContext\Application\Remote\ActionsRouter
        arguments:
            - {bitbucket: '@regis.app.remote.bitbucket_actions', github: '@regis.app.remote.github_actions' }
