repositories_list:
    path:      /repositories
    defaults:  { _controller: RegisBackendBundle:Repositories:list }
    methods:   GET

repositories_new:
    path:      /repositories/new
    defaults:  { _controller: RegisBackendBundle:Repositories:new }
    methods:   GET|POST

repositories_edit:
    path:      /repositories/{identifier}/edit
    defaults:  { _controller: RegisBackendBundle:Repositories:edit }
    requirements: { identifier: ".+/.+" }
    methods:   GET|POST