repositories_list:
    path:      /repositories
    defaults:  { _controller: RegisBackendBundle:Repositories:list }
    methods:   GET

repositories_detail:
    path:      /repositories/{identifier}
    defaults:  { _controller: RegisBackendBundle:Repositories:detail }
    requirements: { identifier: "[^/]+/[^/]+" }
    methods:   GET

repositories_setup_webhook:
    path:      /repositories/{identifier}/webhook/setup
    defaults:  { _controller: RegisBackendBundle:Repositories:setupWebhook }
    requirements: { identifier: "[^/]+/[^/]+" }
    methods:   POST

repositories_new:
    path:      /repositories/new
    defaults:  { _controller: RegisBackendBundle:Repositories:new }
    methods:   GET|POST

repositories_edit:
    path:      /repositories/{identifier}/edit
    defaults:  { _controller: RegisBackendBundle:Repositories:edit }
    requirements: { identifier: "[^/]+/[^/]+" }
    methods:   GET|POST